---
logging:
  level:
    org:
      springframework:
        security: DEBUG

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

sentry:
  dsn: https://examplePublicKey@o0.ingest.sentry.io/0
  tracesSampleRate: 1.0

# server:
#   servlet:
#     context-path: /api
